-- MySQL Script generated by MySQL Workbench
-- Tue Jul 26 16:45:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`fabricantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fabricantes` (
  `fabricantes` CHAR(20) NOT NULL,
  PRIMARY KEY (`fabricantes`));


-- -----------------------------------------------------
-- Table `mydb`.`bicicletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bicicletas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fabricante` CHAR(20) NOT NULL,
  `precio` INT NOT NULL,
  `año` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fabricante_idx` (`fabricante` ASC) VISIBLE,
  CONSTRAINT `fabricante`
    FOREIGN KEY (`fabricante`)
    REFERENCES `mydb`.`fabricantes` (`fabricantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prov_nombre` CHAR(20) NOT NULL,
  `prov_direccion` CHAR(20) NOT NULL,
  `prov_telefono` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`motocicletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`motocicletas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fabricante` CHAR(20) NOT NULL,
  `proveedor` INT NOT NULL,
  `precio` INT NOT NULL,
  `autonomia` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Proveedor_idx` (`proveedor` ASC) VISIBLE,
  INDEX `fabricante_idx` (`fabricante` ASC) VISIBLE,
  CONSTRAINT `proveedor`
    FOREIGN KEY (`proveedor`)
    REFERENCES `mydb`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fabricante`
    FOREIGN KEY (`fabricante`)
    REFERENCES `mydb`.`fabricantes` (`fabricantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `alias` CHAR(20) NOT NULL,
  `nombre` CHAR(20) NOT NULL,
  `Apellido` CHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `celular` CHAR(20) NOT NULL,
  `contraseña` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`alias`));


-- -----------------------------------------------------
-- Table `mydb`.`intension_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`intension_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alias` CHAR(20) NOT NULL,
  `fabricante` CHAR(20) NOT NULL,
  `fecha_hora` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `alias_idx` (`alias` ASC) VISIBLE,
  INDEX `fabricante_idx` (`fabricante` ASC) VISIBLE,
  CONSTRAINT `alias`
    FOREIGN KEY (`alias`)
    REFERENCES `mydb`.`clientes` (`alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fabricante`
    FOREIGN KEY (`fabricante`)
    REFERENCES `mydb`.`fabricantes` (`fabricantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
